#!/bin/bash
SCHRODINGER=/scr/wick/builds/2020-4/build; export SCHRODINGER; SCHRODINGER_SRC=/scr/wick/builds/2020-4/source; export SCHRODINGER_SRC; SCHRODINGER_LIB=/software/lib/; export SCHRODINGER_LIB
export QTDIR="$SCHRODINGER_LIB/Darwin-x86_64/qt-*"
alias designer='open $QTDIR/bin/Designer.app'
# alias nb="export SCHRODINGER="$(bash ~/laterest_build.sh -b NB)""
# alias ob="export SCHRODINGER="$(bash ~/laterest_build.sh)""
alias schenv="source $SCHRODINGER_SRC/mmshare/build_env"
alias mae="$SCHRODINGER/maestro -console"
alias schro="echo $SCHRODINGER"
# Building variables and aliases
alias buildinger.sh='${SCHRODINGER_SRC}/mmshare/build_tools/buildinger.sh'

#colors and current directory
export PS1="[\t]\[$(tput sgr0)\]\[\033[38;5;160m\]\u@\h:\[$(tput sgr0)\]\[\033[38;5;6m\]\w\[$(tput sgr0)\] \[$(tput sgr0)\]"

alias ls='ls -G'
LS_COLORS='di=32:fi=0:ln=31:pi=5:so=5:bd=5:cd=5:or=31:mi=0:ex=35:*.rpm=90'
export LS_COLORS

# Avoid duplicates
export HISTCONTROL=ignoredups:erasedups

# Setting PATH for Python 3.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
export PATH

#adding utils to PATH
PATH="/utils/bin:${PATH}"
export PATH
